import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author manuel
 */
public class InterfazCripto extends javax.swing.JFrame {

    public InterfazCripto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OptionButtonGroup = new javax.swing.ButtonGroup();
        TitleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OutputTextArea = new javax.swing.JTextArea();
        MessageLabel = new javax.swing.JLabel();
        OutputLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        EncryptRadioButton = new javax.swing.JRadioButton();
        DecryptRadioButton = new javax.swing.JRadioButton();
        ShiftLabel1 = new javax.swing.JLabel();
        ShitTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        UploadToggleButton1 = new javax.swing.JToggleButton();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLabel.setText("Cryptography Activity 1");

        OutputTextArea.setColumns(20);
        OutputTextArea.setRows(5);
        jScrollPane2.setViewportView(OutputTextArea);

        MessageLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MessageLabel.setText("Input");

        OutputLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OutputLabel.setText("Output");

        UserLabel.setText("Ortiz Salazar Manuel Eduardo");

        DeleteButton.setBackground(new java.awt.Color(255, 153, 153));
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        OptionButtonGroup.add(EncryptRadioButton);
        EncryptRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EncryptRadioButton.setText("Encrypt");
        EncryptRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncryptRadioButtonActionPerformed(evt);
            }
        });

        OptionButtonGroup.add(DecryptRadioButton);
        DecryptRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DecryptRadioButton.setText("Decrypt");
        DecryptRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecryptRadioButtonActionPerformed(evt);
            }
        });

        ShiftLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ShiftLabel1.setText("Key");

        ShitTextField.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EncryptRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DecryptRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(ShiftLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ShitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EncryptRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DecryptRadioButton)
                    .addComponent(ShitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShiftLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        UploadToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UploadToggleButton1.setText("Upload file");
        UploadToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(UploadToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(UploadToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        OKButton.setBackground(new java.awt.Color(153, 255, 153));
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(MessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OutputLabel)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputLabel)
                    .addComponent(MessageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(UserLabel)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EncryptRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncryptRadioButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EncryptRadioButtonActionPerformed

    private void DecryptRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecryptRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DecryptRadioButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        String Direction = "C:/Users/manue/Desktop/Marley_C.txt";
        String DirectionDec = "C:/Users/manue/Desktop/Marley_C_D.txt";
        
        FileWriter fichero = null;

        if (EncryptRadioButton.isSelected() == true) {
            //OPEN FILE
            try {
                fichero = new FileWriter(Direction);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCripto.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Write FILE
            try {
                BufferedWriter writer = new BufferedWriter(fichero);
                String key = OutputTextArea.getText();

                //int shift = Integer.parseInt(ShitTextField.getText());
                char letters[] = key.toCharArray();

                //Encrypt Message
                for (int i = 0; i < letters.length; i++) {
                    letters[i] = (char) (letters[i] + (char) 1);
                }
                String crypt = String.valueOf(letters);
                writer.write(crypt);

                writer.close();
            } catch (Exception ex) {
            }
        } else if (DecryptRadioButton.isSelected() == true) {
            //OPEN FILE
            try {
                fichero = new FileWriter(DirectionDec);
            } catch (IOException ex) {
                Logger.getLogger(InterfazCripto.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Write FILE
            try {
                BufferedWriter writer = new BufferedWriter(fichero);
                String key = OutputTextArea.getText();

                //int shift = Integer.parseInt(ShitTextField.getText());
                char letters[] = key.toCharArray();

                //Decrypt Message
                for (int i = 0; i < letters.length; i++) {
                    letters[i] = (char) (letters[i] - (char) 1);
                }
                String decrypt = String.valueOf(letters);
                writer.write(decrypt);
                writer.close();
                
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_OKButtonActionPerformed

    private void UploadToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadToggleButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo = fc.getSelectedFile();

        try {
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            String text = "";
            String line = "";

            while ((line = br.readLine()) != null) {
                text += line + "\n";
            }
            OutputTextArea.setText(text);
            JOptionPane.showMessageDialog(null, "OK!");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_UploadToggleButton1ActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        OutputTextArea.setText("");
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCripto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DecryptRadioButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JRadioButton EncryptRadioButton;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JButton OKButton;
    private javax.swing.ButtonGroup OptionButtonGroup;
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JTextArea OutputTextArea;
    private javax.swing.JLabel ShiftLabel1;
    private javax.swing.JTextField ShitTextField;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JToggleButton UploadToggleButton1;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
